[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Enable Netlify's Next.js Runtime
[functions]
  directory = ".netlify/functions-internal"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/api/*"
  [headers.values]
    cache-control = "public, max-age=0, must-revalidate"
